blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('create/', views.CreateBlogView, name='create_post'),
    path('<slug>/', views.BlogDetailView, name='detail_post'),
    path('<slug>/edit', views.EditBlogView, name='edit'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('account.urls')),
    path('blog/', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils.text import slugify
from django.conf import settings
from django.db.models.signals import post_delete, pre_save
from django.dispatch import receiver

# Create your models here.

def upload_location(instance, filename):
    file_path = 'blog/{author_id}/{title}-{filename}'.format(
        author_id = str(instance.author.id), title = str(instance.title), filename=filename
    )
    return file_path

class BlogPost(models.Model):
    title = models.CharField(max_length=250, null=False, blank=False)
    body = models.TextField(max_length=5000, null=False, blank=False)
    image = models.ImageField(upload_to=upload_location, null=False, blank=False)
    date_published = models.DateTimeField(auto_now_add=True, verbose_name="date published")    
    date_updated = models.DateTimeField(auto_now=True, verbose_name="date updated")    
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    slug =  models.SlugField(blank=True, unique=True)

    def __str__(self):
        return self.title + " | " + str(self.author)


@receiver(post_delete, sender=BlogPost)
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False)

def pre_save_blog_post_receiver(sender, instance,**kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.author.username + "-" + instance.title)

pre_save.connect(pre_save_blog_post_receiver, sender=BlogPost)

blog/forms.py
from django import forms
from blog. models import BlogPost

class CreateBlogPostForm(forms.ModelForm):

    class Meta:
        model = BlogPost
        fields = ('title', 'body', 'image')
        exclude = []

class UpdateBlogPostForm(forms.ModelForm):

    class Meta:
        model = BlogPost
        fields = ('title', 'body', 'image')
        exclude = []

    def save(self, commit=True):
        blog_post = self.instance
        blog_post.title = self.cleaned_data['title']
        blog_post.body = self.cleaned_data['body']
        
        if self.cleaned_data['image']:
            blog_post.image = self.cleaned_data['image']

        if commit:
            blog_post.save()

        return blog_post 

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from blog. models import BlogPost
from blog. forms import CreateBlogPostForm, UpdateBlogPostForm
from account.models import Account
from django.db.models import Q
from django.http import HttpResponse
# Create your views here.

def CreateBlogView(request):
    user = request.user
    if not user.is_authenticated:
        return redirect('must_auth')

    form = CreateBlogPostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        obj = form.save(commit=False)
        author = Account.objects.filter(email=user.email).first()
        obj.author = author
        obj.save()
        form = CreateBlogPostForm()
    
    return render(request, 'blog/create_blog.html', {'form':form})


def BlogDetailView(request, slug):
    blog_post = get_object_or_404(BlogPost, slug=slug)
    return render(request, 'blog/detail_view.html', {'blog_post':blog_post})

def EditBlogView(request, slug):
    context={}
    user = request.user
    if not user.is_authenticated:
        return redirect('must_auth')

    blog_post = get_object_or_404(BlogPost, slug=slug)

    if blog_post.author != user:
        return HttpResponse("You are Not Author of this post.")

    if request.POST:
        form = UpdateBlogPostForm(request.POST or None, request.FILES or None, instance=blog_post)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            context['success'] = "updated"
            blog_post = obj

    form = UpdateBlogPostForm(
        initial={
            'title':blog_post.title,
            'body':blog_post.body,
            'image':blog_post.image,
        }
    )
    context['form'] = form
    return render(request, 'blog/edit_blog.html', context)


def get_blog_queryset(query=None):
    queryset = []
    queries = query.split(" ") # python install 2019 = [python, install, 2019]
    for q in queries:
        posts = BlogPost.objects.filter(
                Q(title__icontains=q) | 
                Q(body__icontains=q)
            ).distinct()

        for post in posts:
            queryset.append(post)

    return list(set(queryset))

blog/templates/blog/snippets/blog_post_pagination.html
<!-- FILTERED Pagination -->


<div class="d-flex flex-column m-auto pagination mt-5 ">
    <nav aria-label="Page navigation">
    <ul class="pagination pg-grey justify-content-center">
        {% if blog_posts.has_previous %}
            <li class="page-item">
              <a class="page-link bg-warning " href="?{% if query %}q={{query}}&{% endif %}page={{ blog_posts.previous_page_number }}">&laquo; Previous</a>
            </li>
        {% endif %}
    
        {% for i in blog_posts.paginator.page_range %}
            {% if blog_posts.number == i %}
                <li class="page-item "><a class="page-link bg-warning">{{ i }}</a></li>
            {% else %}
                <li class="page-item" ><a class="page-link bg-warning" href="?{% if query %}q={{query}}&{% endif %}page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        
        {% if blog_posts.has_next %}
            <li class="page-item">
              <a class="page-link bg-warning" href="?{% if query %}q={{query}}&{% endif %}page={{ blog_posts.next_page_number }}">Next</a>
            </li>
            <li class="page-item">
              <a class="page-link bg-warning"  href="?{% if query %}q={{query}}&{% endif %}page={{ blog_posts.paginator.num_pages }}">Last &raquo;</a>
            </li>
        {% endif %}
    </ul>
    </nav>
</div>
    <!-- end pagination-->

blog/templates/blog/snippets/blog_post_snippet.html
{% if blog_post %}
<div class="container">
    <div class="row">
        <!-- End For Header -->
        <!-- FOR CARDS -->
        <!-- For 1st Card -->
        <div class="col-lg-16 mg-4 mt-3">
            <div class="card">
                <div class="card-body">
					<!-- For Image Link To Details Page -->
                    <a href="{% url 'blog:detail_post' post.slug %}">
						<img class="card-img-top" src="{{blog_post.image.url}}">
					</a>
					<!-- END -->
					<!-- Title Link -->
                    <a href="{% url 'blog:detail_post' post.slug %}">
						<h3 class="card-title mb-1">{{blog_post.title}}</h3>
					</a>
                    <hr>
					<!-- END -->
					<!-- Paragraph of 180 word -->
					<p class="card-text">{{blog_post.body|safe|truncatechars:180}}</p>
					<!-- end -->
                    {% if blog_post.author == request.user %}
                        <a href="{% url 'blog:edit' blog_post.slug %}" class="btn btn-warning">EDIT</a>
                    {% endif %}
                    <div class="card-footer text-muted">
                        {{blog_post.date_published}} by {{blog_post.author}}
                    </div>
                </div>
            </div>
        </div>
        <!-- End CARDS -->
    </div>
</div>

{% else %}

<div class="container">
	<div class="row">
		<div class="card m-auto">
			<div class="card-body mt-2 mb-2">
				<h2 class="card-title">No results</h2>
				<p class="card-text">There were no results matching the search: "{{query}}"</p>
			</div>
		</div>
	</div>
</div>

{% endif %}