blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('create/', views.CreateBlogView, name='create_post'),
    path('<slug>/', views.BlogDetailView, name='detail_post'),
    path('<slug>/edit', views.EditBlogView, name='edit'),
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Home_view, name='home'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('account.urls')),
    path('blog/', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render, reverse
from account.models import Account
from blog.models import BlogPost           
from operator import attrgetter
from blog.views import get_blog_queryset
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
# Create your views here.

BLOG_POSTS_PER_PAGE = 5

def Home_view(request):
    context = {}
    query = ""
    if request.GET:
        query = request.GET.get('q', '')
        context['query'] = str(query)
    blog_posts = sorted(get_blog_queryset(query), key=attrgetter('date_updated'), reverse=True)

    page = request.GET.get('page', 1)
    blog_posts_paginator = Paginator(blog_posts, BLOG_POSTS_PER_PAGE)
    try:
        blog_posts = blog_posts_paginator.page(page)
    except PageNotAnInteger:
        blog_posts = blog_posts_paginator.page(BLOG_POSTS_PER_PAGE)
    except EmptyPage:
        blog_posts = blog_posts_paginator.page(blog_posts_paginator.num_pages)

    context['blog_posts'] = blog_posts


    return render(request, 'main/home.html', context)

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block body %}

<div class="container">
	<div class="row">
		<!-- blog feed -->
		<div class="left-column col-lg-7 offset-lg-1">
			<!-- Blog posts-->
			{% if blog_posts %}
				{% for post in blog_posts %}
					<div class="blog-post-container">
						{% include 'blog/snippets/blog_post_snippet.html' with blog_post=post %}
					</div>
				{% endfor %}
			{% else %}
				<div class="blog-post-container">
					{% include 'blog/snippets/blog_post_snippet.html' with query=query %}
				</div>
			{% endif %}

			<!-- Paginations -->
			{% include 'blog/snippets/blog_post_pagination.html' with blog_posts=blog_posts %}
			<!-- End Blog posts-->
		</div>
		<!-- end blog feed -->

		<!-- Right 'create post' column  -->
		
		<div class="right-column col-lg-3 d-lg-flex d-none flex-column mt-3">
			<div class="card create-post-bar d-flex flex-column p-3">
				<p class="m-auto"><a class="btn btn-warning" href="{% url 'blog:create_post' %}">Create post</a></p>
			</div>
		</div>
		<!-- end Right 'create post' column  -->

	</div>
</div>

{% endblock body %}